spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
document:
  server:
    local-dir: /tmp/document
    server-url: http://document-server:8080
    document-server-root-url: http://onlyoffice


